### ISSUE TITLE
Fixevi 2

### ISSUE THREAD

**Issue by codeAdrian** [ivan-baljkas/frontend_zadatak_1#3]
Solidno si to odradio. Funkcionalnost i stilovi su dobri. Evo par prijedloga

U CollectionTable komponenti imaš neke importe koje ne koristiš - Component i TableItem, isto tako u Pagination, SearchForm i TableItem. Component možeš maknuti.
```
import React, { Component } from 'react'
import { TableItem } from './TableItem';
```

Možeš test wrappati u `<h1>` u `<header>`. H1-H6 su ti zaglavlja. https://www.w3schools.com/html/html_headings.asp

```
<header>Collection</header>
```

**Comment by ivan-baljkas** [comment]
Popravljeno sve.
